[tool.poetry]
name = "ml-components"
version = "0.1.0"
description = ""
authors = ["sakairi-nobuyuki <SAKAIRI.Nobuyuki@gmail.com>"]
readme = "README.md"
packages = [{include = "ml_components"}]

[tool.poetry.dependencies]
python = "^3.10"
torch = "^2.0.0"
opencv-python = "^4.7.0.72"
numpy = "^1.24.3"
typer = "^0.7.0"
black = "^23.3.0"
isort = "^5.12.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
pytest-cov = "^4.0.0"
boto3 = "^1.26.123"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
