[tool.rye]
name = "ml_components"
version = "0.1.0"
description = ""

[tool.poetry]
name = "ml-components"
version = "0.1.0"
description = ""
authors = ["sakairi-nobuyuki <SAKAIRI.Nobuyuki@gmail.com>"]
readme = "README.md"
packages = [{include = "ml_components"}]

[tool.poetry.dependencies]
python = "^3.10"
opencv-python = "^4.7.0.72"
numpy = "^1.24.3"
typer = "^0.7.0"
black = "^23.3.0"
isort = "^5.12.0"
pytest = "^7.3.1"
boto3 = "^1.26.123"
tqdm = "^4.65.0"
onnx = "^1.14.0"
moto = "^4.1.10"
pydantic = "^2.1.1"
scikit-learn = "^1.3.2"


[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
pytest-cov = "^4.0.0"
boto3 = "^1.26.123"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 90
exclude = '''
(
     \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | venv
    | \.idea
    | \.vscode
    | _build
    | buck-out
    | build
    | dist
    | migrations
    | db
 )
 '''

[tool.isort]
profile = "black"
line_length = 90
skip_glob = "*/migrations/*.py,*/__init__.py"